image: openjdk:17-jdk

default:
  tags:
    #- comsc-ci
    #- general-docker
    - toby-runner

stages:
  - assemble
  - build
  - publish
  - deploy

before_script:
  - echo $GRADLE_HOME
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/
  - microdnf install findutils
  - chmod +x gradlew
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

assemble:gradle:
  stage: assemble
  script:
    - ./gradlew assemble

build:gradle:
  stage: build
  script:
    - export PROD_PASSWORD="$PROD_PASSWORD"
    - ./gradlew build -PjvmArgs='-DPROD_PASSWORD=cardiff'
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - ./build/reports/tests/
      - ./build/libs/*.jar
      - ./build/libs/*.log
    expire_in: 4 week


pages:

  stage: publish
  script:
    - pwd
    - mv ./build/reports/tests/ public
    - mv ./build/libs/*.jar public
    - pwd
    - ls -lR public

  artifacts:
    paths:
      - public


