DROP DATABASE IF EXISTS graphium;

CREATE DATABASE IF NOT EXISTS graphium;

USE graphium;

DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS SUPERVISOR;
DROP TABLE IF EXISTS CHECK_INS;
DROP TABLE IF EXISTS ONE_TO_ONE;
DROP TABLE IF EXISTS NOTES;



CREATE TABLE IF NOT EXISTS EMPLOYEES
(
    ID              INTEGER AUTO_INCREMENT NOT NULL,
    NAME            VARCHAR(200)           NOT NULL,
    EMAIL           VARCHAR(30)            NOT NULL,
    EMPLOYEE_ROLE   VARCHAR(30)            NOT NULL,
    PASSWORD_HASH   VARCHAR(64)            NOT NULL,
    SUPERVISOR_ID   INTEGER                NOT NULL,
    PRIMARY KEY (`ID`)
    )
    ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS SUPERVISOR
(
    ID              INTEGER AUTO_INCREMENT NOT NULL,
    NAME            VARCHAR(100)           NOT NULL,
    EMAIL           VARCHAR(30)            NOT NULL,
    PASSWORD_HASH   VARCHAR(128)           NOT NULL,
    PRIMARY KEY (`ID`)
    )
    ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS CHECK_INS
(
    ID    INTEGER AUTO_INCREMENT NOT NULL,
    EMPLOYEE_ID    INTEGER                NOT NULL,
    SCORE          VARCHAR(100)           NOT NULL,
    CHECK_IN_DATE  DATE                   NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES EMPLOYEES(`ID`)
    )
    ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS ONE_TO_ONE
(
    ID              INTEGER AUTO_INCREMENT NOT NULL,
    EMPLOYEE_ID     INTEGER                NOT NULL,
    SUPERVISOR_ID   INTEGER                NOT NULL,
    ONE_TO_ONE_DATE DATE                   NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES EMPLOYEES(`ID`),
    FOREIGN KEY (`SUPERVISOR_ID`) REFERENCES SUPERVISOR(`ID`)
    )
    ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS NOTES
(
    ID               INTEGER AUTO_INCREMENT NOT NULL,
    ONE_TO_ONE_ID    INTEGER                NOT NULL,
    NOTE             VARCHAR(300)           NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`ONE_TO_ONE_ID`) REFERENCES ONE_TO_ONE(`ID`)
    )
    ENGINE = INNODB